apiVersion: v1
kind: Namespace
metadata:
  name: artist-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service
  namespace: artist-service
  labels:
    app: artist-service
spec:
  selector:
    matchLabels:
      app: artist-service
  replicas: 1
  template:
    metadata:
      labels:
        app: artist-service
    spec:
      containers:
        - name: artist-service
          image: ghcr.io/spotify-portal-public-demo/artist-service:main-cbf3c2fc-1755203523 # {"$imagepolicy": "flux-system:artist-service"}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: artist-service
  namespace: artist-service
  labels:
    app: artist-service
spec:
  clusterIP: None
  selector:
    app: artist-service
  ports:
    - name: grpc
      port: 9090
